### ISSUE TITLE
logo for build it bigger

### ISSUE THREAD

**Issue by hafizahmmed** [TonMarton/BuildItBigger#1]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![build-it-bigger-01](https://user-images.githubusercontent.com/38810169/40267767-7c30b862-5b84-11e8-9d38-6952b961a31a.jpg)

**Comment by TonMarton** [comment]
No thanks, this is a demo project.
